### ISSUE TITLE
Setting server url

### ISSUE THREAD

**Issue by cyclehacker** [rcdevs/nextcloud_openotp_auth#1]
I enable your app after installing php7.0-soap and php-ldap and everything appears to be fine except I don't know what to insert in the field: 'OpenOTP server URL' in the app configuration settings. My nextcloud instance runs on my own domain.com/nextcloud/. Can you point me in the right direction please?

**Comment by rcdevs** [comment]
Hello,
This is a plugin for an integration to Nextcould for our free IAM/MFA server named OpenOTP, you can find all the details in the vendor website: www.rcdevs.com, licence free with all features included up to 50 users. 
Regards
