### ISSUE TITLE
Change log not updated

### ISSUE THREAD

**Issue by nicovd737** [rcdevs/nextcloud_openotp_auth#17]
Hello,

I see in nextcloud that there is a new openotp release (1.28.3) but i can't find any information about what is changed thru this update. I'd like to have info before upgrading and having suprises.

Could you provide change history ?

Thanks for your help.

**Comment by rcdevs** [comment]
Hello Nicovd737
Just checked and I confirm only dependencies are updated, _1.28.3 Update dependencies_, (a warning received from Github).
About the modified PHP files, it's only because a different code formatting, nothing else.
Best regards
EJB

**Comment by nicovd737** [comment]
Hello,
Thanks.
You can close this issue.
Best regards,
Nico
