### ISSUE TITLE
Integrity check fails with Nextcloud 13.0.5

### ISSUE THREAD

**Issue by LeutholdF** [rcdevs/nextcloud_openotp_auth#2]
Here the message of the integrity Check:
Results
=======
- twofactor_rcdevsopenotp
	- FILE_MISSING
		- l10n/.tx/config

Raw output
==========
Array
(
    [twofactor_rcdevsopenotp] => Array
        (
            [FILE_MISSING] => Array
                (
                    [l10n/.tx/config] => Array
                        (
                            [expected] => 5ad14bb93e25fd93ebbd96e1e995367db065d11953f0c3ac707962098956f1a9f5534a7dcceb834ebfb4a6b3edd7f6a8c6cbddd01c052bbb61fe951c779f2fca
                            [current] => 
                        )

                )

        )

)

**Comment by ChristophWurst** [comment]
Ref https://github.com/nextcloud/twofactor_totp/issues/261 https://github.com/nextcloud/twofactor_totp/issues/260 https://github.com/nextcloud/twofactor_totp/issues/255

**Comment by rcdevs** [comment]
Hi,
Integrity check should be corrected in v1.0.3 of OpenOTP Plugin for Nextcloud 13
