### ISSUE TITLE
Nextcloud 19 compatibility

### ISSUE THREAD

**Issue by qhrfkr** [rcdevs/nextcloud_openotp_auth#4]
Hello!

Could you add compatibility with version 19 of NextCloud?

Best Regards,
Dmitry

**Comment by rcdevscare** [comment]
Thank You for reaching out to RCDevs. We will enhance our NextCloud plugin to support this version.

**Comment by qhrfkr** [comment]
Glad to hear that!
I'll look forward to this improvement.

**Comment by JernejSS** [comment]
Looking forward for this plugin refresh.
We are now waiting for new release, but also we are waiting with RCDEVS user license expansion.

**Comment by rcdevs** [comment]
The plugin has been refreshed and compatibility is now extended up to Nextcloud 23
