### ISSUE TITLE
login redirection with edge

### ISSUE THREAD

**Issue by LeutholdF** [rcdevs/nextcloud_openotp_auth#7]
The successful login redirection is not working with latest edge release as it blocks the redirect script in Content-Security-Policy.

**Comment by rcdevs** [comment]
Hello. We just released the version 1.4.3 that should fix the issue. Best regards.

**Comment by LeutholdF** [comment]
Hello,
just upgraded to release 1.4.3 and everything works now.
Many thanks and best regards
